/**
 *   Copyright 2021 Alibaba, Inc. and its affiliates. All Rights Reserved.
 * 
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *   
 *       http://www.apache.org/licenses/LICENSE-2.0
 *   
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.

   \author   Hechong.xyf
   \date     Oct 2020
   \brief    Common definition for bilin engine
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/common.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//! Types of Operation
type OperationType int32

const (
	OperationType_OP_INSERT OperationType = 0 // Insert Operation
	OperationType_OP_UPDATE OperationType = 1 // Update Operation
	OperationType_OP_DELETE OperationType = 2 // Delete Operation
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OP_INSERT",
		1: "OP_UPDATE",
		2: "OP_DELETE",
	}
	OperationType_value = map[string]int32{
		"OP_INSERT": 0,
		"OP_UPDATE": 1,
		"OP_DELETE": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

//! Types of Feature (same as Proxima)
type FeatureType int32

const (
	FeatureType_FT_UNDEFINED FeatureType = 0 // Undefined
	FeatureType_FT_BINARY32  FeatureType = 1 // 32-bits Binary
	FeatureType_FT_BINARY64  FeatureType = 2 // 64-bits Binary
	FeatureType_FT_FP16      FeatureType = 3 // 16-bits Float Number
	FeatureType_FT_FP32      FeatureType = 4 // 32-bits Float Number
	FeatureType_FT_FP64      FeatureType = 5 // 64-bits Float Number
	FeatureType_FT_INT8      FeatureType = 6 // 8-bits Integer
	FeatureType_FT_INT16     FeatureType = 7 // 16-bits Integer
	FeatureType_FT_INT4      FeatureType = 8 // 4-bits Integer
)

// Enum value maps for FeatureType.
var (
	FeatureType_name = map[int32]string{
		0: "FT_UNDEFINED",
		1: "FT_BINARY32",
		2: "FT_BINARY64",
		3: "FT_FP16",
		4: "FT_FP32",
		5: "FT_FP64",
		6: "FT_INT8",
		7: "FT_INT16",
		8: "FT_INT4",
	}
	FeatureType_value = map[string]int32{
		"FT_UNDEFINED": 0,
		"FT_BINARY32":  1,
		"FT_BINARY64":  2,
		"FT_FP16":      3,
		"FT_FP32":      4,
		"FT_FP64":      5,
		"FT_INT8":      6,
		"FT_INT16":     7,
		"FT_INT4":      8,
	}
)

func (x FeatureType) Enum() *FeatureType {
	p := new(FeatureType)
	*p = x
	return p
}

func (x FeatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (FeatureType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x FeatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureType.Descriptor instead.
func (FeatureType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

//! Types of Index
type IndexType int32

const (
	IndexType_IT_UNDEFINED           IndexType = 0 // Undefined
	IndexType_IT_PROXIMA_GRAPH_INDEX IndexType = 1 // Proxima Graph Index
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "IT_UNDEFINED",
		1: "IT_PROXIMA_GRAPH_INDEX",
	}
	IndexType_value = map[string]int32{
		"IT_UNDEFINED":           0,
		"IT_PROXIMA_GRAPH_INDEX": 1,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[2].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[2]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

type DataType int32

const (
	DataType_DT_UNDEFINED       DataType = 0
	DataType_DT_BINARY          DataType = 1
	DataType_DT_STRING          DataType = 2
	DataType_DT_BOOL            DataType = 3
	DataType_DT_INT32           DataType = 4
	DataType_DT_INT64           DataType = 5
	DataType_DT_UINT32          DataType = 6
	DataType_DT_UINT64          DataType = 7
	DataType_DT_FLOAT           DataType = 8
	DataType_DT_DOUBLE          DataType = 9
	DataType_DT_VECTOR_BINARY32 DataType = 20
	DataType_DT_VECTOR_BINARY64 DataType = 21
	DataType_DT_VECTOR_FP16     DataType = 22
	DataType_DT_VECTOR_FP32     DataType = 23
	DataType_DT_VECTOR_FP64     DataType = 24
	DataType_DT_VECTOR_INT4     DataType = 25
	DataType_DT_VECTOR_INT8     DataType = 26
	DataType_DT_VECTOR_INT16    DataType = 27
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "DT_UNDEFINED",
		1:  "DT_BINARY",
		2:  "DT_STRING",
		3:  "DT_BOOL",
		4:  "DT_INT32",
		5:  "DT_INT64",
		6:  "DT_UINT32",
		7:  "DT_UINT64",
		8:  "DT_FLOAT",
		9:  "DT_DOUBLE",
		20: "DT_VECTOR_BINARY32",
		21: "DT_VECTOR_BINARY64",
		22: "DT_VECTOR_FP16",
		23: "DT_VECTOR_FP32",
		24: "DT_VECTOR_FP64",
		25: "DT_VECTOR_INT4",
		26: "DT_VECTOR_INT8",
		27: "DT_VECTOR_INT16",
	}
	DataType_value = map[string]int32{
		"DT_UNDEFINED":       0,
		"DT_BINARY":          1,
		"DT_STRING":          2,
		"DT_BOOL":            3,
		"DT_INT32":           4,
		"DT_INT64":           5,
		"DT_UINT32":          6,
		"DT_UINT64":          7,
		"DT_FLOAT":           8,
		"DT_DOUBLE":          9,
		"DT_VECTOR_BINARY32": 20,
		"DT_VECTOR_BINARY64": 21,
		"DT_VECTOR_FP16":     22,
		"DT_VECTOR_FP32":     23,
		"DT_VECTOR_FP64":     24,
		"DT_VECTOR_INT4":     25,
		"DT_VECTOR_INT8":     26,
		"DT_VECTOR_INT16":    27,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[3].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[3]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

//! Types of Field
type GenericValueMeta_FieldType int32

const (
	GenericValueMeta_FT_BYTES  GenericValueMeta_FieldType = 0 // bytes
	GenericValueMeta_FT_STRING GenericValueMeta_FieldType = 1 // string
	GenericValueMeta_FT_BOOL   GenericValueMeta_FieldType = 2 // bool
	GenericValueMeta_FT_INT32  GenericValueMeta_FieldType = 3 // int32
	GenericValueMeta_FT_INT64  GenericValueMeta_FieldType = 4 // int64
	GenericValueMeta_FT_UINT32 GenericValueMeta_FieldType = 5 // uint32
	GenericValueMeta_FT_UINT64 GenericValueMeta_FieldType = 6 // uint64
	GenericValueMeta_FT_FLOAT  GenericValueMeta_FieldType = 7 // float
	GenericValueMeta_FT_DOUBLE GenericValueMeta_FieldType = 8 // double float
)

// Enum value maps for GenericValueMeta_FieldType.
var (
	GenericValueMeta_FieldType_name = map[int32]string{
		0: "FT_BYTES",
		1: "FT_STRING",
		2: "FT_BOOL",
		3: "FT_INT32",
		4: "FT_INT64",
		5: "FT_UINT32",
		6: "FT_UINT64",
		7: "FT_FLOAT",
		8: "FT_DOUBLE",
	}
	GenericValueMeta_FieldType_value = map[string]int32{
		"FT_BYTES":  0,
		"FT_STRING": 1,
		"FT_BOOL":   2,
		"FT_INT32":  3,
		"FT_INT64":  4,
		"FT_UINT32": 5,
		"FT_UINT64": 6,
		"FT_FLOAT":  7,
		"FT_DOUBLE": 8,
	}
)

func (x GenericValueMeta_FieldType) Enum() *GenericValueMeta_FieldType {
	p := new(GenericValueMeta_FieldType)
	*p = x
	return p
}

func (x GenericValueMeta_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenericValueMeta_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[4].Descriptor()
}

func (GenericValueMeta_FieldType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[4]
}

func (x GenericValueMeta_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenericValueMeta_FieldType.Descriptor instead.
func (GenericValueMeta_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2, 0}
}

//! Union of Generic Value
type GenericValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOneof:
	//	*GenericValue_BytesValue
	//	*GenericValue_StringValue
	//	*GenericValue_BoolValue
	//	*GenericValue_Int32Value
	//	*GenericValue_Int64Value
	//	*GenericValue_Uint32Value
	//	*GenericValue_Uint64Value
	//	*GenericValue_FloatValue
	//	*GenericValue_DoubleValue
	ValueOneof isGenericValue_ValueOneof `protobuf_oneof:"value_oneof"`
}

func (x *GenericValue) Reset() {
	*x = GenericValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericValue) ProtoMessage() {}

func (x *GenericValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericValue.ProtoReflect.Descriptor instead.
func (*GenericValue) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (m *GenericValue) GetValueOneof() isGenericValue_ValueOneof {
	if m != nil {
		return m.ValueOneof
	}
	return nil
}

func (x *GenericValue) GetBytesValue() []byte {
	if x, ok := x.GetValueOneof().(*GenericValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *GenericValue) GetStringValue() string {
	if x, ok := x.GetValueOneof().(*GenericValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *GenericValue) GetBoolValue() bool {
	if x, ok := x.GetValueOneof().(*GenericValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *GenericValue) GetInt32Value() int32 {
	if x, ok := x.GetValueOneof().(*GenericValue_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *GenericValue) GetInt64Value() int64 {
	if x, ok := x.GetValueOneof().(*GenericValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *GenericValue) GetUint32Value() uint32 {
	if x, ok := x.GetValueOneof().(*GenericValue_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *GenericValue) GetUint64Value() uint64 {
	if x, ok := x.GetValueOneof().(*GenericValue_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *GenericValue) GetFloatValue() float32 {
	if x, ok := x.GetValueOneof().(*GenericValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *GenericValue) GetDoubleValue() float64 {
	if x, ok := x.GetValueOneof().(*GenericValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

type isGenericValue_ValueOneof interface {
	isGenericValue_ValueOneof()
}

type GenericValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,1,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type GenericValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type GenericValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type GenericValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type GenericValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type GenericValue_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,6,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type GenericValue_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,7,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type GenericValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,8,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type GenericValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,9,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

func (*GenericValue_BytesValue) isGenericValue_ValueOneof() {}

func (*GenericValue_StringValue) isGenericValue_ValueOneof() {}

func (*GenericValue_BoolValue) isGenericValue_ValueOneof() {}

func (*GenericValue_Int32Value) isGenericValue_ValueOneof() {}

func (*GenericValue_Int64Value) isGenericValue_ValueOneof() {}

func (*GenericValue_Uint32Value) isGenericValue_ValueOneof() {}

func (*GenericValue_Uint64Value) isGenericValue_ValueOneof() {}

func (*GenericValue_FloatValue) isGenericValue_ValueOneof() {}

func (*GenericValue_DoubleValue) isGenericValue_ValueOneof() {}

//! Message of Generic Value List
type GenericValueList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*GenericValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GenericValueList) Reset() {
	*x = GenericValueList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericValueList) ProtoMessage() {}

func (x *GenericValueList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericValueList.ProtoReflect.Descriptor instead.
func (*GenericValueList) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *GenericValueList) GetValues() []*GenericValue {
	if x != nil {
		return x.Values
	}
	return nil
}

//! Message of Generic Value Meta
type GenericValueMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName string                     `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType GenericValueMeta_FieldType `protobuf:"varint,2,opt,name=field_type,json=fieldType,proto3,enum=proxima.be.proto.GenericValueMeta_FieldType" json:"field_type,omitempty"`
}

func (x *GenericValueMeta) Reset() {
	*x = GenericValueMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericValueMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericValueMeta) ProtoMessage() {}

func (x *GenericValueMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericValueMeta.ProtoReflect.Descriptor instead.
func (*GenericValueMeta) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *GenericValueMeta) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *GenericValueMeta) GetFieldType() GenericValueMeta_FieldType {
	if x != nil {
		return x.FieldType
	}
	return GenericValueMeta_FT_BYTES
}

//! Message of Generic Key-Value Pair
type GenericKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *GenericValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GenericKeyValue) Reset() {
	*x = GenericKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericKeyValue) ProtoMessage() {}

func (x *GenericKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericKeyValue.ProtoReflect.Descriptor instead.
func (*GenericKeyValue) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *GenericKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenericKeyValue) GetValue() *GenericValue {
	if x != nil {
		return x.Value
	}
	return nil
}

//! Message of IndexParameter, which used to customize index, and query
type KeyValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

//! Common Response
type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

//! Common Http Request for admin
type HttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{7}
}

//! Common Http Response for admin
type HttpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{8}
}

var File_proto_common_proto protoreflect.FileDescriptor

var file_proto_common_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x2e, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b,
	0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x4a, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x69, 0x6d, 0x61, 0x2e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x8d, 0x02, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x70, 0x72,
	0x6f, 0x78, 0x69, 0x6d, 0x61, 0x2e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x54, 0x5f, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x46, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x54,
	0x5f, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x55,
	0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x55, 0x49,
	0x4e, 0x54, 0x36, 0x34, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x54, 0x5f, 0x46, 0x4c, 0x4f,
	0x41, 0x54, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x54, 0x5f, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x10, 0x08, 0x22, 0x59, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d,
	0x61, 0x2e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36,
	0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x48, 0x74,
	0x74, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x74, 0x74,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x3c, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50,
	0x5f, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x5f,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x5f, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x90, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x54, 0x5f, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x54, 0x5f,
	0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x33, 0x32, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x54,
	0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x36, 0x34, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x46,
	0x54, 0x5f, 0x46, 0x50, 0x31, 0x36, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x46,
	0x50, 0x33, 0x32, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x46, 0x50, 0x36, 0x34,
	0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x38, 0x10, 0x06, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10, 0x07, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x34, 0x10, 0x08, 0x2a, 0x39, 0x0a, 0x09, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x54, 0x5f, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x54, 0x5f,
	0x50, 0x52, 0x4f, 0x58, 0x49, 0x4d, 0x41, 0x5f, 0x47, 0x52, 0x41, 0x50, 0x48, 0x5f, 0x49, 0x4e,
	0x44, 0x45, 0x58, 0x10, 0x01, 0x2a, 0xc7, 0x02, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x54, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x54, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52,
	0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x54, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x54, 0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12,
	0x0c, 0x0a, 0x08, 0x44, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x44, 0x54, 0x5f, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x44,
	0x54, 0x5f, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x54,
	0x5f, 0x55, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x54, 0x5f,
	0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x54, 0x5f, 0x44, 0x4f,
	0x55, 0x42, 0x4c, 0x45, 0x10, 0x09, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43,
	0x54, 0x4f, 0x52, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x33, 0x32, 0x10, 0x14, 0x12, 0x16,
	0x0a, 0x12, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x42, 0x49, 0x4e, 0x41,
	0x52, 0x59, 0x36, 0x34, 0x10, 0x15, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43,
	0x54, 0x4f, 0x52, 0x5f, 0x46, 0x50, 0x31, 0x36, 0x10, 0x16, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x54,
	0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x46, 0x50, 0x33, 0x32, 0x10, 0x17, 0x12, 0x12,
	0x0a, 0x0e, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x46, 0x50, 0x36, 0x34,
	0x10, 0x18, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f,
	0x49, 0x4e, 0x54, 0x34, 0x10, 0x19, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x54, 0x5f, 0x56, 0x45, 0x43,
	0x54, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x54, 0x38, 0x10, 0x1a, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x54,
	0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10, 0x1b, 0x42,
	0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x6d, 0x61, 0x2f, 0x73, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData = file_proto_common_proto_rawDesc
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_proto_rawDescData)
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_common_proto_goTypes = []interface{}{
	(OperationType)(0),              // 0: proxima.be.proto.OperationType
	(FeatureType)(0),                // 1: proxima.be.proto.FeatureType
	(IndexType)(0),                  // 2: proxima.be.proto.IndexType
	(DataType)(0),                   // 3: proxima.be.proto.DataType
	(GenericValueMeta_FieldType)(0), // 4: proxima.be.proto.GenericValueMeta.FieldType
	(*GenericValue)(nil),            // 5: proxima.be.proto.GenericValue
	(*GenericValueList)(nil),        // 6: proxima.be.proto.GenericValueList
	(*GenericValueMeta)(nil),        // 7: proxima.be.proto.GenericValueMeta
	(*GenericKeyValue)(nil),         // 8: proxima.be.proto.GenericKeyValue
	(*KeyValuePair)(nil),            // 9: proxima.be.proto.KeyValuePair
	(*CommonResponse)(nil),          // 10: proxima.be.proto.CommonResponse
	(*Status)(nil),                  // 11: proxima.be.proto.Status
	(*HttpRequest)(nil),             // 12: proxima.be.proto.HttpRequest
	(*HttpResponse)(nil),            // 13: proxima.be.proto.HttpResponse
}
var file_proto_common_proto_depIdxs = []int32{
	5, // 0: proxima.be.proto.GenericValueList.values:type_name -> proxima.be.proto.GenericValue
	4, // 1: proxima.be.proto.GenericValueMeta.field_type:type_name -> proxima.be.proto.GenericValueMeta.FieldType
	5, // 2: proxima.be.proto.GenericKeyValue.value:type_name -> proxima.be.proto.GenericValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericValueList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericValueMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValuePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GenericValue_BytesValue)(nil),
		(*GenericValue_StringValue)(nil),
		(*GenericValue_BoolValue)(nil),
		(*GenericValue_Int32Value)(nil),
		(*GenericValue_Int64Value)(nil),
		(*GenericValue_Uint32Value)(nil),
		(*GenericValue_Uint64Value)(nil),
		(*GenericValue_FloatValue)(nil),
		(*GenericValue_DoubleValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_rawDesc = nil
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
