{
 "title": "Proxima SE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"proxima-se\"}[1m])",
     "legendFormat": "avg_process_cpu_usage"
    },
    {
     "expr": "avg_over_time(process_cpu_usage_system{job=\"proxima-se\"}[1m])",
     "legendFormat": "avg_process_cpu_usage_system"
    },
    {
     "expr": "avg_over_time(process_cpu_usage_user{job=\"proxima-se\"}[1m])",
     "legendFormat": "avg_process_cpu_usage_user"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_memory_resident{job=\"proxima-se\"}[1m])",
     "legendFormat": "average memory"
    }
   ]
  },
  { "title": "vector query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "vector query success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(se_query_success_count_second)",
     "legendFormat": "success qps"
    },
    {
     "expr": "sum(se_query_failure_count_second)",
     "legendFormat": "failure qps"
    },
    {
     "expr": "sum(se_query_success_count_second)/(sum(se_query_success_count_second)+sum(se_query_failure_count_second))",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "vector query latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(se_query_http_request_latency)",
     "legendFormat": "http"
    },
    {
     "expr": "avg(se_query_grpc_request_latency)",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "vector query qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(se_query_http_request_qps)", "legendFormat": "http qps" },
    { "expr": "sum(se_query_grpc_request_qps)", "legendFormat": "grpc qps" }
   ]
  },
  {
   "title": "vector query latency percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "se_query_http_request_latency_80",
     "legendFormat": "http_p80"
    },
    {
     "expr": "se_query_http_request_latency_90",
     "legendFormat": "http_p90"
    },
    {
     "expr": "se_query_http_request_latency_999",
     "legendFormat": "http_p999"
    },
    {
     "expr": "se_query_grpc_request_latency_80",
     "legendFormat": "grpc_p80"
    },
    {
     "expr": "se_query_http_request_latency_90",
     "legendFormat": "grpc_p90"
    },
    {
     "expr": "se_query_http_request_latency_999",
     "legendFormat": "grpc_p999"
    }
   ]
  },
  {
   "title": "vector query batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(se_query_batch_second)", "legendFormat": "average batch" }
   ]
  },
  { "title": "insert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "insert success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(se_write_success_count_second)",
     "legendFormat": "success qps"
    },
    {
     "expr": "sum(se_write_failure_count_second)",
     "legendFormat": "failure qps"
    },
    {
     "expr": "sum(se_write_success_count_second)/(sum(se_write_success_count_second)+sum(se_write_failure_count_second))",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "insert latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(se_write_http_request_latency)",
     "legendFormat": "http"
    },
    {
     "expr": "avg(se_write_grpc_request_latency)",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "insert qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(se_write_http_request_qps)", "legendFormat": "http qps" },
    { "expr": "sum(se_write_grpc_request_qps)", "legendFormat": "grpc qps" }
   ]
  },
  {
   "title": "insert latency percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "se_write_http_request_latency_80",
     "legendFormat": "http_p80"
    },
    {
     "expr": "se_write_http_request_latency_90",
     "legendFormat": "http_p90"
    },
    {
     "expr": "se_write_http_request_latency_999",
     "legendFormat": "http_p999"
    },
    {
     "expr": "se_write_grpc_request_latency_80",
     "legendFormat": "grpc_p80"
    },
    {
     "expr": "se_write_http_request_latency_90",
     "legendFormat": "grpc_p90"
    },
    {
     "expr": "se_write_http_request_latency_999",
     "legendFormat": "grpc_p999"
    }
   ]
  },
  {
   "title": "insert batch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(se_write_batch_second)", "legendFormat": "average batch" }
   ]
  },
  {
   "title": "insert count by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(se_write_op_insert_count_second)",
     "legendFormat": "insert_count"
    },
    {
     "expr": "sum(se_write_op_update_count_second)",
     "legendFormat": "update_count"
    },
    {
     "expr": "sum(se_write_op_delete_count_second)",
     "legendFormat": "delete_count"
    }
   ]
  },
  { "title": "pk query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "pk query success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(se_get_document_success_count_second)",
     "legendFormat": "success qps"
    },
    {
     "expr": "sum(se_get_document_failure_count_second)",
     "legendFormat": "failure qps"
    },
    {
     "expr": "sum(se_get_document_success_count_second)/(sum(se_get_document_success_count_second)+sum(se_get_document_failure_count_second))",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "pk query latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(se_get_document_http_request_latency)",
     "legendFormat": "http"
    },
    {
     "expr": "avg(se_get_document_grpc_request_latency)",
     "legendFormat": "grpc"
    }
   ]
  },
  {
   "title": "pk query qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(se_get_document_http_request_qps)",
     "legendFormat": "http qps"
    },
    {
     "expr": "sum(se_get_document_grpc_request_qps)",
     "legendFormat": "grpc qps"
    }
   ]
  },
  {
   "title": "pk query latency percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "se_get_document_http_request_latency_80",
     "legendFormat": "http_p80"
    },
    {
     "expr": "se_get_document_http_request_latency_90",
     "legendFormat": "http_p90"
    },
    {
     "expr": "se_get_document_http_request_latency_999",
     "legendFormat": "http_p999"
    },
    {
     "expr": "se_get_document_grpc_request_latency_80",
     "legendFormat": "grpc_p80"
    },
    {
     "expr": "se_get_document_http_request_latency_90",
     "legendFormat": "grpc_p90"
    },
    {
     "expr": "se_get_document_http_request_latency_999",
     "legendFormat": "grpc_p999"
    }
   ]
  }
 ]
}